version: '2'

volumes:
  mongo_db_composer:

services:
  composer:
    restart: always
    image: idgis/geoide-composer:${COMPOSER_VERSION}
    ports:
      - "${PORT}:80"
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
      - ROOT_URL=${ROOT_URL}
      - MONGO_URL=mongodb://composer-db/geoide-composer
    networks:
      - geoide-composer
      
  composer-db:
    restart: always
    image: mongo:3.2.11
    volumes:
      - mongo_db_composer:/data/db
    networks:
      - geoide-composer
      
networks:
  geoide-composer:
    external: true